// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCo0Y8wWDE_teMW1Ogtq_1XVEw-WJt61c',
    appId: '1:869401035628:web:bfa301746730319adc2949',
    messagingSenderId: '869401035628',
    projectId: 'smarthomeiot-5a1e7',
    authDomain: 'smarthomeiot-5a1e7.firebaseapp.com',
    storageBucket: 'smarthomeiot-5a1e7.firebasestorage.app',
    measurementId: 'G-DB1EXQV5E6',
    databaseURL: "https://smarthomeiot-5a1e7-default-rtdb.firebaseio.com",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBYAsugO2CvKTjppUYXH8BY6OVoaMx20o',
    appId: '1:869401035628:android:68c92d8fd84a81f7dc2949',
    messagingSenderId: '869401035628',
    projectId: 'smarthomeiot-5a1e7',
    storageBucket: 'smarthomeiot-5a1e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2Arjk1bEzSztOFvnkb_9kzV0IRO1JE1g',
    appId: '1:869401035628:ios:e9233c2136a217a8dc2949',
    messagingSenderId: '869401035628',
    projectId: 'smarthomeiot-5a1e7',
    storageBucket: 'smarthomeiot-5a1e7.firebasestorage.app',
    iosBundleId: 'com.example.smartHomeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2Arjk1bEzSztOFvnkb_9kzV0IRO1JE1g',
    appId: '1:869401035628:ios:e9233c2136a217a8dc2949',
    messagingSenderId: '869401035628',
    projectId: 'smarthomeiot-5a1e7',
    storageBucket: 'smarthomeiot-5a1e7.firebasestorage.app',
    iosBundleId: 'com.example.smartHomeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCo0Y8wWDE_teMW1Ogtq_1XVEw-WJt61c',
    appId: '1:869401035628:web:03504c591ba4aabddc2949',
    messagingSenderId: '869401035628',
    projectId: 'smarthomeiot-5a1e7',
    authDomain: 'smarthomeiot-5a1e7.firebaseapp.com',
    storageBucket: 'smarthomeiot-5a1e7.firebasestorage.app',
    measurementId: 'G-NJNQW7Z9CF',
  );
}
